### PR TITLE
Update to v14 (and other stuff)

### PR DESCRIPTION
**Pull request by lolollllo**
- Updates all the code from v13 to v14
- Updates dependencies to latest versions
- Removes imports that weren't used

### CODE REVIEW

**Comment by lolollllo** [comment]
@Darker-Ink

**Comment by Darker-Ink** [comment]
Hey, Thanks for the pull request. It looks good. Just got to ask have you verified it works? I currently do not have the time to test this. If someone is able to test it and confirm it works with a few tests i.e running some commands etc I will merge it!

**Comment by lolollllo** [comment]
> Hey, Thanks for the pull request. It looks good. Just got to ask have you verified it works? I currently do not have the time to test this. If someone is able to test it and confirm it works with a few tests i.e running some commands etc I will merge it!

Alright, I'll test it and let you know today

**Comment by lolollllo** [comment]
Tested Commands:
- [ ] example       
- [ ] help
- [ ] ping 
- [ ] punishments 
- [x] report
- [ ] stats
- [ ] no sub-commands under `user` 
- [ ] no sub-commands under `ticket` 
- [ ] no sub-commands under `suggestion` 
- [x] staff/ban
- [ ] staff/donate
- [x] staff/kick
- [x] staff/mute
- [x] staff/unmute 
- [ ] staff/warn
- [ ] no sub-commands under `server` 
- [x] dev/eval

**Comment by lolollllo** [comment]
Hi @Darker-Ink, I've tested all the commands I Could test. I don't have a pterodactyl panel so I could not test the commands under server, user & other commands such as stats.

**Comment by Darker-Ink** [comment]
Looks good, I'll merge it.

**Pull request merged**
